### ISSUE TITLE
Warning C4244 in hlml_functions_vector.inl

### ISSUE THREAD

**Issue by Flave229** [floorman/HLML#4]
The following error occurs multiple times for many functions in this file:
`warning C4244: 'return': conversion from 'int32_t' to 'float', possible loss of data`

**Comment by floorman** [comment]
Fix for this in dev branch at `0dcbe21`.

I'll move it into release once we've verified it works for Flave.

**Comment by Flave229** [comment]
Yep! Works for me on the above commit. Feel free to close when merged into main :)

**Comment by floorman** [comment]
I added MSVC compile support.  I'll setup Travis tomorrow.  There should be no MSVC compile related issues after that.

**Comment by floorman** [comment]
Fixed.
