### ISSUE TITLE
Identical Bool Sizes Between Compilers

### ISSUE THREAD

**Issue by Flave229** [floorman/HLML#5]
The size of a bool can change depending on what compiler is used to compile the program (Or even defined by the user).

HLML ideally needs some way to always guarantee that its bool types are the same size. My use case for this would be sending data to a shader via a uniform buffer, data may become misaligned when using different compilers to target different platforms.

**Comment by floorman** [comment]
This was something I forgot to put a TODO on during day 1.

The main problem here is that `stdint.h` doesn't give a `bool32` type so people generally make their own, which means that coming up with a non-intrusive/non-conflicting bool type is difficult.

I'll add one with the name `bool32_t`, and if people complain that it conflicts then we'll deal with it then.

**Comment by floorman** [comment]
Fixed in [v0.3.1](https://github.com/floorman/HLML/releases/tag/v0.3.1).
